app.title=javafx-crypt-tool
app.version=${project.version}
app.githubRepositoryUrl=https://github.com/ValerioGc/java-crypt-tool
window.width=900
window.height=760
window.resizable=false
view.padding=22
